name: agu2021
channels:
    - conda-forge
    - defaults
dependencies:
    - pygmt=0.5.0
    - jupyter
    - jupytext
    # Development dependencies
    - make
    - black
    - blackdoc
    - docformatter
    - isort>=5