name: agu2021
channels:
    - conda-forge
    - defaults
dependencies:
    - pygmt
    - jupyter
    - jupytext
    # Development dependencies
    - make
    - black
    - blackdoc
    - docformatter
    - isort>=5